package com.drs.agent.service.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * ExperienceTemplate DTO
 *
 * Template generated by Claude for a new experience entry.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ExperienceTemplate {

    /**
     * Problem type classification
     */
    private String problemType;

    /**
     * Keywords for search
     */
    private List<String> keywords;

    /**
     * Summary of the problem (one sentence)
     */
    private String summary;

    /**
     * Diagnosis chain steps
     */
    private List<DiagnosisStep> diagnosisChain;

    /**
     * Root cause patterns
     */
    private List<RootCauseTemplate> rootCauses;

    /**
     * Estimated success rate (0.0 - 1.0)
     */
    private double estimatedSuccessRate;

    /**
     * Applicable scenarios
     */
    private List<String> applicableScenarios;

    /**
     * Expert tips
     */
    private List<String> expertTips;

    /**
     * Solutions applied
     */
    private List<SolutionTemplate> solutions;

    /**
     * Diagnosis step template
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class DiagnosisStep {
        private int step;
        private String action;
        private String tool;
        private String params;
        private List<String> keyOutputs;
    }

    /**
     * Root cause template
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class RootCauseTemplate {
        private String pattern;
        private String regex;
        private String cause;
        private String solution;
        private String frequency;
    }

    /**
     * Solution template
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class SolutionTemplate {
        private String description;
        private List<String> steps;
        private boolean automationPossible;
    }
}